package com.personnel.api;

import com.personnel.model.*;
import com.personnel.service.PersonnelStore;
import com.personnel.service.SessionService;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.stream.Collectors;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api")
public class PersonnelController {
  private final BCryptPasswordEncoder passwords = new BCryptPasswordEncoder();
  private final PersonnelStore store;
  private final SessionService sessions;
  private static final DateTimeFormatter TS_FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

  public PersonnelController(PersonnelStore store, SessionService sessions) {
    this.store = store; this.sessions = sessions;
  }

  @PostMapping("/auth/login") public Map<String,Object> login(@Valid @RequestBody LoginRequest body){
    var a = store.findAccount(body.username());
    if(a==null || !a.isEnabled() || !passwords.matches(body.password(), a.getPasswordHash())) throw new ApiException(HttpStatus.UNAUTHORIZED,"账号或密码错误，或账号已停用");
    String token = sessions.issue(a.getUsername());
    return Map.of("token", token, "user", user(a));
  }
  @PostMapping("/auth/logout") public void logout(@RequestHeader(value="Authorization",required=false) String header){ if(header!=null) sessions.revoke(header.replace("Bearer ","")); }
  @GetMapping("/auth/me") public Map<String,Object> me(@RequestHeader(value="Authorization",required=false) String header){ return user(current(header)); }
  @PutMapping("/auth/password") public void password(@RequestHeader(value="Authorization",required=false) String header, @RequestBody Map<String,String> body){
    var a = current(header);
    if(!passwords.matches(body.getOrDefault("currentPassword",""), a.getPasswordHash())) throw new ApiException(HttpStatus.BAD_REQUEST,"当前密码不正确");
    String next = body.getOrDefault("newPassword","");
    if(next.length()<8) throw new ApiException(HttpStatus.BAD_REQUEST,"新密码至少为 8 位");
    store.resetPassword(a.getUsername(), passwords.encode(next));
    sessions.revokeAll(a.getUsername());
  }
  @GetMapping("/dashboard") public Map<String,Object> dashboard(@RequestHeader(value="Authorization",required=false) String h){
    admin(h);
    var employees = store.allEmployees();
    long active = employees.stream().filter(e->"ACTIVE".equals(e.getStatus())).count();
    var dist = store.allDepartments().stream().map(d->Map.of("name",d.getName(),"count",(Object)employees.stream().filter(e->"ACTIVE".equals(e.getStatus()) && d.getId().equals(e.getDepartmentId())).count())).toList();
    var recent = store.allChanges().stream().sorted(Comparator.comparing((Change c)->c.getOccurredAt()).reversed()).limit(8).map(this::changeDto).toList();
    return Map.of("totalEmployees", active, "activeEmployees", active, "resignedEmployees", employees.size()-active, "departmentCount", store.allDepartments().size(), "positionCount", store.allPositions().size(), "departmentDistribution", dist, "recentChanges", recent);
  }
  @GetMapping("/departments") public List<Map<String,Object>> departments(@RequestHeader(value="Authorization",required=false)String h){ admin(h); return store.allDepartments().stream().map(this::departmentDto).toList(); }
  @GetMapping("/positions") public List<Map<String,Object>> positions(@RequestHeader(value="Authorization",required=false)String h, @RequestParam(defaultValue="") String departmentId, @RequestParam(defaultValue="") String name){ admin(h); var src = departmentId.isBlank() ? store.allPositions() : store.positionsByDepartment(departmentId); if(!name.isBlank()) src = src.stream().filter(p->p.getName().toLowerCase().contains(name.toLowerCase())).toList(); return src.stream().map(this::positionDto).toList(); }
  @PostMapping("/departments") public Map<String,Object> createDepartment(@RequestHeader(value="Authorization",required=false)String h, @RequestBody Map<String,String>b){ admin(h); String name=required(b,"name"); if(store.allDepartments().stream().anyMatch(d->d.getName().equals(name))) throw new ApiException(HttpStatus.CONFLICT,"部门名称已存在"); var d=new Department("d-"+UUID.randomUUID(),name,Objects.toString(b.get("description"),"")); store.saveDepartment(d); return departmentDto(d); }
  @PutMapping("/departments/{id}") public Map<String,Object> updateDepartment(@RequestHeader(value="Authorization",required=false)String h, @PathVariable String id, @RequestBody Map<String,String>b){ admin(h); var old=store.findDepartment(id); if(old==null) throw new ApiException(HttpStatus.NOT_FOUND,"部门不存在"); String name=required(b,"name"); if(store.allDepartments().stream().anyMatch(d->!d.getId().equals(id)&&d.getName().equals(name))) throw new ApiException(HttpStatus.CONFLICT,"部门名称已存在"); var d=new Department(id,name,Objects.toString(b.get("description"),"")); store.saveDepartment(d); return departmentDto(d); }
  @DeleteMapping("/departments/{id}") public void deleteDepartment(@RequestHeader(value="Authorization",required=false)String h, @PathVariable String id){ admin(h); if(store.allEmployees().stream().anyMatch(e->e.getDepartmentId().equals(id)) || store.allChanges().stream().anyMatch(c->id.equals(c.getBeforeDepartmentId())||id.equals(c.getAfterDepartmentId()))) throw new ApiException(HttpStatus.CONFLICT,"部门已被员工或历史记录引用，不能删除"); store.deleteDepartment(id); }
  @PostMapping("/positions") public Map<String,Object> createPosition(@RequestHeader(value="Authorization",required=false)String h, @RequestBody Map<String,String>b){ admin(h); String name=required(b,"name"); if(store.allPositions().stream().anyMatch(p->p.getName().equals(name))) throw new ApiException(HttpStatus.CONFLICT,"岗位名称已存在"); String deptId=Objects.toString(b.get("departmentId"),""); if(!deptId.isBlank()&&store.findDepartment(deptId)==null) throw new ApiException(HttpStatus.BAD_REQUEST,"部门不存在"); var p=new Position("p-"+UUID.randomUUID(),name,Objects.toString(b.get("description"),""),deptId.isBlank()?null:deptId); store.savePosition(p); return positionDto(p); }
  @PutMapping("/positions/{id}") public Map<String,Object> updatePosition(@RequestHeader(value="Authorization",required=false)String h, @PathVariable String id, @RequestBody Map<String,String>b){ admin(h); var old=store.findPosition(id); if(old==null) throw new ApiException(HttpStatus.NOT_FOUND,"岗位不存在"); String name=required(b,"name"); if(store.allPositions().stream().anyMatch(p->!p.getId().equals(id)&&p.getName().equals(name))) throw new ApiException(HttpStatus.CONFLICT,"岗位名称已存在"); String deptId=Objects.toString(b.get("departmentId"),""); if(!deptId.isBlank()&&store.findDepartment(deptId)==null) throw new ApiException(HttpStatus.BAD_REQUEST,"部门不存在"); var p=new Position(id,name,Objects.toString(b.get("description"),""),deptId.isBlank()?null:deptId); store.savePosition(p); return positionDto(p); }
  @DeleteMapping("/positions/{id}") public void deletePosition(@RequestHeader(value="Authorization",required=false)String h, @PathVariable String id){ admin(h); if(store.allEmployees().stream().anyMatch(e->e.getPositionId().equals(id)) || store.allChanges().stream().anyMatch(c->id.equals(c.getBeforePositionId())||id.equals(c.getAfterPositionId()))) throw new ApiException(HttpStatus.CONFLICT,"岗位已被员工或历史记录引用，不能删除"); store.deletePosition(id); }
  @GetMapping("/employees") public Map<String,Object> list(@RequestHeader(value="Authorization",required=false) String header, @RequestParam(defaultValue="")String keyword, @RequestParam(defaultValue="")String departmentId, @RequestParam(defaultValue="")String status, @RequestParam(defaultValue="1")int page, @RequestParam(defaultValue="10")int size){ admin(header); var found=store.allEmployees().stream().filter(e->keyword.isBlank()||e.getEmployeeNo().contains(keyword)||e.getName().contains(keyword)||(e.getPhone()!=null&&e.getPhone().contains(keyword))).filter(e->departmentId.isBlank()||e.getDepartmentId().equals(departmentId)).filter(e->status.isBlank()||e.getStatus().equals(status)).toList(); int from=Math.min(Math.max(page-1,0)*size,found.size()),to=Math.min(from+size,found.size()); return Map.of("content",found.subList(from,to).stream().map(this::employeeDto).toList(),"total",found.size(),"page",page,"size",size); }
  @GetMapping("/employees/{id}") public Map<String,Object> employee(@RequestHeader(value="Authorization",required=false) String header, @PathVariable String id){ admin(header); return employeeDto(requireEmployee(id)); }
  @PostMapping("/employees") public Map<String,Object> create(@RequestHeader(value="Authorization",required=false) String header, @RequestBody Map<String,String> b){ admin(header); if(store.allEmployees().stream().anyMatch(e->e.getEmployeeNo().equals(b.get("employeeNo")))) throw new ApiException(HttpStatus.CONFLICT,"工号已存在"); verifyOrg(b); LocalDateTime now=LocalDateTime.now(); var e=new Employee("e-"+UUID.randomUUID(),required(b,"employeeNo"),required(b,"name"),b.get("phone"),b.get("email"),b.get("address"),b.get("education"),b.get("departmentId"),b.get("positionId"),required(b,"hireDate"),"ACTIVE",now,now); store.createEmployee(e, current(header).getUsername()); return employeeDto(e); }
  @PutMapping("/employees/{id}") public Map<String,Object> update(@RequestHeader(value="Authorization",required=false) String header, @PathVariable String id, @RequestBody Map<String,String>b){ admin(header); var e=requireEmployee(id); e.setName(required(b,"name")); e.setPhone(b.get("phone")); e.setEmail(b.get("email")); e.setAddress(b.get("address")); e.setEducation(b.get("education")); e.setHireDate(required(b,"hireDate")); e.setUpdatedAt(LocalDateTime.now()); store.saveEmployee(e); return employeeDto(e); }
  @PostMapping("/employees/{id}/transfer") public Map<String,Object> transfer(@RequestHeader(value="Authorization",required=false)String h, @PathVariable String id, @RequestBody Map<String,String>b){ var a=admin(h); var e=requireEmployee(id); if(!"ACTIVE".equals(e.getStatus())) throw new ApiException(HttpStatus.BAD_REQUEST,"离职员工不能调岗"); verifyOrg(b); if(e.getDepartmentId().equals(b.get("departmentId"))&&e.getPositionId().equals(b.get("positionId"))) throw new ApiException(HttpStatus.BAD_REQUEST,"部门或岗位至少变更一项"); store.transferEmployee(id, b.get("departmentId"), b.get("positionId"), tsParam(b.get("occurredAt")), required(b,"reason"), a.getUsername()); return employeeDto(requireEmployee(id)); }
  @PostMapping("/employees/{id}/resign") public Map<String,Object> resign(@RequestHeader(value="Authorization",required=false)String h, @PathVariable String id, @RequestBody Map<String,String>b){ var a=admin(h); var e=requireEmployee(id); if(!"ACTIVE".equals(e.getStatus())) throw new ApiException(HttpStatus.BAD_REQUEST,"该员工已离职"); store.resignEmployee(id, tsParam(b.get("occurredAt")), required(b,"reason"), a.getUsername()); for(String uname: store.usernamesByEmployeeId(id)) sessions.revokeAll(uname); return employeeDto(requireEmployee(id)); }
  @GetMapping("/changes") public Map<String,Object> changes(@RequestHeader(value="Authorization",required=false)String h, @RequestParam(defaultValue="")String keyword, @RequestParam(defaultValue="")String type){ admin(h); var data=store.allChanges().stream().filter(c->keyword.isBlank()||c.getEmployeeName().contains(keyword)||c.getEmployeeNo().contains(keyword)).filter(c->type.isBlank()||c.getType().equals(type)).sorted(Comparator.comparing((Change c)->c.getOccurredAt()).reversed()).map(this::changeDto).toList(); return Map.of("content",data,"total",data.size(),"page",1,"size",data.size()); }
  @GetMapping("/accounts") public List<Map<String,Object>> accountList(@RequestHeader(value="Authorization",required=false)String h){ admin(h); return store.employeeAccounts().stream().map(this::accountDto).toList(); }
  @PostMapping("/accounts") public Map<String,Object> createAccount(@RequestHeader(value="Authorization",required=false)String h, @RequestBody Map<String,String>b){ admin(h); String username=required(b,"username"),employeeId=required(b,"employeeId"),password=required(b,"password"); if(store.findAccount(username)!=null) throw new ApiException(HttpStatus.CONFLICT,"登录账号已存在"); var e=requireEmployee(employeeId); if(!"ACTIVE".equals(e.getStatus())) throw new ApiException(HttpStatus.BAD_REQUEST,"离职员工不能创建账号"); if(!store.usernamesByEmployeeId(employeeId).isEmpty()) throw new ApiException(HttpStatus.CONFLICT,"该员工已关联职员账号"); store.createAccount(username, passwords.encode(password), employeeId); return accountDto(store.findAccount(username)); }
  @PostMapping("/accounts/{username}/disable") public void disable(@RequestHeader(value="Authorization",required=false)String h, @PathVariable String username){ admin(h); var a=store.findAccount(username); if(a==null||!"EMPLOYEE".equals(a.getRole())) throw new ApiException(HttpStatus.NOT_FOUND,"职员账号不存在"); store.disableAccount(username); sessions.revokeAll(username); }
  @PostMapping("/accounts/{username}/reset-password") public void resetPassword(@RequestHeader(value="Authorization",required=false)String h, @PathVariable String username, @RequestBody Map<String,String>b){ admin(h); var a=store.findAccount(username); if(a==null||!"EMPLOYEE".equals(a.getRole())) throw new ApiException(HttpStatus.NOT_FOUND,"职员账号不存在"); store.resetPassword(username, passwords.encode(required(b,"password"))); sessions.revokeAll(username); }
  @GetMapping("/profile") public Map<String,Object> profile(@RequestHeader(value="Authorization",required=false) String header){ var a=current(header); if(!"EMPLOYEE".equals(a.getRole())||a.getEmployeeId()==null) throw new ApiException(HttpStatus.FORBIDDEN,"当前账号没有职员档案权限"); return employeeDto(requireEmployee(a.getEmployeeId())); }
  @PutMapping("/profile") public Map<String,Object> updateProfile(@RequestHeader(value="Authorization",required=false)String header, @RequestBody Map<String,String>b){ var a=current(header); if(!"EMPLOYEE".equals(a.getRole())||a.getEmployeeId()==null) throw new ApiException(HttpStatus.FORBIDDEN,"当前账号没有职员档案权限"); var e=requireEmployee(a.getEmployeeId()); e.setPhone(b.get("phone")); e.setEmail(b.get("email")); e.setAddress(b.get("address")); e.setEducation(b.get("education")); e.setUpdatedAt(LocalDateTime.now()); store.saveEmployee(e); return employeeDto(e); }
  private Account current(String header){ if(header==null||!header.startsWith("Bearer ")) throw new ApiException(HttpStatus.UNAUTHORIZED,"请先登录"); var u=sessions.usernameOf(header.substring(7)); var a=u==null?null:store.findAccount(u); if(a==null||!a.isEnabled()) throw new ApiException(HttpStatus.UNAUTHORIZED,"登录已失效"); return a; }
  private Account admin(String header){ var a=current(header); if(!"ADMIN".equals(a.getRole())) throw new ApiException(HttpStatus.FORBIDDEN,"需要管理员权限"); return a; }
  private Employee requireEmployee(String id){ var e=store.findEmployee(id); if(e==null) throw new ApiException(HttpStatus.NOT_FOUND,"员工不存在"); return e; }
  private String required(Map<String,String>b,String k){ var v=b.get(k); if(v==null||v.isBlank()) throw new ApiException(HttpStatus.BAD_REQUEST,k+"不能为空"); return v; }
  private void verifyOrg(Map<String,String>b){ String deptId=b.get("departmentId"), posId=b.get("positionId"); if(!store.allDepartments().stream().anyMatch(d->d.getId().equals(deptId))) throw new ApiException(HttpStatus.BAD_REQUEST,"部门无效"); Position pos=store.allPositions().stream().filter(p->p.getId().equals(posId)).findFirst().orElse(null); if(pos==null) throw new ApiException(HttpStatus.BAD_REQUEST,"岗位无效"); if(pos.getDepartmentId()!=null && !pos.getDepartmentId().equals(deptId)) throw new ApiException(HttpStatus.BAD_REQUEST,"所选岗位不属于该部门"); }
  private Map<String,Object> user(Account a){ var m=new LinkedHashMap<String,Object>(); m.put("username",a.getUsername()); m.put("role",a.getRole()); if(a.getEmployeeId()!=null) m.put("employeeId",a.getEmployeeId()); return m; }
  private Map<String,Object> employeeDto(Employee e){ var m=new LinkedHashMap<String,Object>(); m.put("id",e.getId()); m.put("employeeNo",e.getEmployeeNo()); m.put("name",e.getName()); m.put("phone",Objects.toString(e.getPhone(),"")); m.put("email",Objects.toString(e.getEmail(),"")); m.put("address",Objects.toString(e.getAddress(),"")); m.put("education",Objects.toString(e.getEducation(),"")); m.put("departmentId",e.getDepartmentId()); m.put("departmentName",deptName(e.getDepartmentId())); m.put("positionId",e.getPositionId()); m.put("positionName",posName(e.getPositionId())); m.put("hireDate",e.getHireDate()); m.put("status",e.getStatus()); m.put("createdAt",e.getCreatedAt()); m.put("updatedAt",e.getUpdatedAt()); return m; }
  private String deptName(String id){ var d=store.findDepartment(id); return d==null?"":d.getName(); }
  private String posName(String id){ var p=store.findPosition(id); return p==null?"":p.getName(); }
  private Map<String,Object> changeDto(Change c){ var r=new LinkedHashMap<String,Object>(); r.put("id",c.getId()); r.put("type",c.getType()); r.put("employeeName",c.getEmployeeName()); r.put("employeeNo",c.getEmployeeNo()); r.put("occurredAt",c.getOccurredAt()); r.put("beforeDepartmentId",c.getBeforeDepartmentId()); r.put("beforePositionId",c.getBeforePositionId()); r.put("afterDepartmentId",c.getAfterDepartmentId()); r.put("afterPositionId",c.getAfterPositionId()); r.put("reason",c.getReason()); r.put("operator",c.getOperator()); return r; }
  private Map<String,Object> departmentDto(Department d){ return Map.of("id",d.getId(),"name",d.getName(),"description",d.getDescription(),"employeeCount",store.allEmployees().stream().filter(e->"ACTIVE".equals(e.getStatus()) && d.getId().equals(e.getDepartmentId())).count()); }
  private Map<String,Object> positionDto(Position p){ return Map.of("id",p.getId(),"name",p.getName(),"description",p.getDescription(),"departmentId",Objects.toString(p.getDepartmentId(),""),"departmentName",deptName(p.getDepartmentId()),"employeeCount",store.allEmployees().stream().filter(e->"ACTIVE".equals(e.getStatus()) && p.getId().equals(e.getPositionId())).count()); }
  private Map<String,Object> accountDto(Account a){ var e=store.findEmployee(a.getEmployeeId()); return Map.of("username",a.getUsername(),"employeeId",a.getEmployeeId(),"employeeNo",e.getEmployeeNo(),"employeeName",e.getName(),"enabled",a.isEnabled()); }
  private String tsParam(String in){ if(in!=null && !in.isBlank()){ if(in.matches("\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}")) return in; if(in.matches("\\d{4}-\\d{2}-\\d{2}")) return in+" 00:00:00"; if(in.contains("T")){ try { return LocalDateTime.parse(in.replace("Z","").replace("T"," "), DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSS")).format(TS_FMT); } catch(Exception ignore){} } } return LocalDateTime.now().format(TS_FMT); }
  record LoginRequest(@NotBlank(message="账号不能为空") String username, @NotBlank(message="密码不能为空") String password){}
}
